name: CI

on:
  push:
    branches: [ main, 'dev/**' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Webots
        run: |
          set -e
          wget -q -O webots.deb https://github.com/cyberbotics/webots/releases/download/R2023a/webots_2023a_amd64.deb
          sudo apt install -y -qq ./webots.deb
          rm -f webots.deb
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cargo Cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
