name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Webots
        run: |
          set -e
          wget -q -O webots.deb https://github.com/cyberbotics/webots/releases/download/R2021b/webots_2021b_amd64.deb
          sudo apt install ./webots.deb
          rm -f webots.deb
      - uses: actions/checkout@v2
      - name: Cargo Cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
